name = "LIMMS"
license = "MIT"
licenselink = "https://limms-tokyo.org"
description = "LIMMS is an international research unit on MEMS and NEMS (Micro- and Nano-Electro-Mechanical Systems) operated in joint names of France, CNRS – INSIS, and Japan, IIS, The University of Tokyo."
homepage = "https://limms-tokyo.org"
demosite = ""
min_version = "0.121.2"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Zeon Studio"
homepage = "https://zeon.studio"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
